language: python

# enable caching of installed packages.
cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

# we don't need any python dependencies, but a ruby one for coverage:
install:
  - gem install coveralls-lcov
  - pip install pytest
  - pip install codecov

# the test command:
script:
  - python setup.py build_ext -i
  - python -m pytest tests
  - make clean
  - CFLAGS="-coverage" python setup.py build_ext -i
  - python -m pytest tests

# but we do need a system library:
addons:
  apt:
    packages:
      - libacl1-dev
      - lcov

after_success:
  - lcov --capture --no-external --directory . --output-file coverage.info
  - COVERALLS_PARALLEL=true coveralls-lcov coverage.info
  - codecov

notifications:
  webhooks: https://coveralls.io/webhook
