language: python

# let's test as many versions as we can!
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "nightly"

# we don't need any python dependencies:
install: true

# the test command:
script: python ./setup.py test

# but we do need a system library:
addons:
  apt:
    packages:
      - libacl1-dev
