language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  include:
    - python: "3.7"
      dist: xenial

# we don't need any python dependencies:
install: true

# the test command:
script: python ./setup.py test

# but we do need a system library:
addons:
  apt:
    packages:
      - libacl1-dev
